#:schema node_modules/wrangler/config-schema.json
name = "workermail"
main = "src/index.ts"
compatibility_date = "2024-12-18"


# Custom domain (optional)
# Uncomment the following lines to use a custom domain
# routes = [
#   { pattern = "YOUR_DOMAIN_ADDRESS", custom_domain = true }
# ]

# Whether to use the Workers URL
# workers_dev = false
# preview_urls = false

# Database binding
# Change `database_name` and `database_id` to match your D1 database
# DO NOT CHANGE `binding` unless you know what you're doing
[[d1_databases]]
binding = "DB"
database_name = "YOUR_DATABASE_NAME"
database_id = "YOUR_DATABASE_ID"